version: "3.8"
services:
  es01:
    image: "docker.elastic.co/elasticsearch/elasticsearch-oss:${ES_VERSION}"
    labels:
     co.elastic.logs/module: elasticsearch
    ports:
      - "${ES_PORT}:9200"
      - "9300:9300"
    environment:
      discovery.type: single-node
      #xpack.security.enabled: false
      ELASTIC_PASSWORD: ${ELASTIC_PASSWORD}
    mem_limit: ${ES_MEM_LIMIT}
    volumes:
      - es-data-01:/usr/share/elasticsearch/data
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
    healthcheck:
      test: ["CMD-SHELL", "curl http://localhost:9200"]
      interval: 15s
      timeout: 30s
      retries: 5
volumes:
  es-data-01:
    driver: local
