version: "3.8"
services:
  es01:
    image: "docker.elastic.co/elasticsearch/elasticsearch-oss:${ES_VERSION}"
    ports:
      - "${ES_PORT}:9200"
    environment:
      - node.name=es01
      - cluster.name=${CLUSTER_NAME}
      - discovery.type=single-node
      - ELASTIC_PASSWORD=${ELASTIC_PASSWORD}
      - bootstrap.memory_lock=true
    mem_limit: ${ES_MEM_LIMIT}
    volumes:
      - "es-data-es01:/usr/share/elasticsearch/data"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    healthcheck:
      test: ["CMD-SHELL", "curl http://localhost:9200"]
      interval: 15s
      timeout: 30s
      retries: 5
volumes:
  es-data-01:
